### ISSUE TITLE
Align section numbers with user need numbers

### ISSUE THREAD

**Issue by matatk** [w3c/apa#58]
It would be really neat, for when people are talking about the XAUR, if the section numbers (within [section 4](https://raw.githack.com/w3c/apa/38a0617945cdd79579be632add45e78d0b78e39c/xaur/index.html#xr-user-needs-and-requirements)) could be made to match the user need numbers.

**This needs to have the XAUR label, but I don't have permissions to make that change on this repo.** 

*[Original feedback email, for reference](https://lists.w3.org/Archives/Public/public-apa-admin/2020Jan/0021.html)*

**Comment by RealJoshue108** [comment]
Thanks @matatk In the current draft they are slightly out of sync - in that '4.2 Immersive semantics and customization' relates to 'User Need 1:' and '4.3 Motion agnostic interactions relates to 'User Need 2:'.

Do you mean they should be '4.1 Immersive semantics and customization' relates to 'User Need 1:' and '4.2 Motion agnostic interactions relates to 'User Need 2:' etc?

**Comment by matatk** [comment]
Hi @RealJoshue108, yes, that's what I was meaning. I was wondering if the content of section 4.1 could just be put under the section 4 heading (though appreciate it's nice to highlight the definition as important)?

**Comment by RealJoshue108** [comment]
Thanks @matatk  we can look at this for the next draft

**Comment by RealJoshue108** [comment]
@matatk I've fixed this in new draft. Reads better (good catch!) 😀

**Comment by matatk** [comment]
That's great. Is the publication of the latest Editor's draft at https://w3c.github.io/apa/xaur/ automated? It's still showing as being from the 17th of February, though I note that it's only been half an hour since you made the change, so I am perhaps a bit over-excited to see it published :-).

**Comment by RealJoshue108** [comment]
He he - I'd hold your horses at this stage. I'll be editing for a bit yet and then there will be a whole CFC and review process etc *grin.
